### PR TITLE
Added a mobile menu using the react-device-detect library.

### PR DESCRIPTION
**Pull request by ibotforwin**
Added a MobileView for the header as well as a BrowserView.

The BrowserView remains the same as the original header, while the MobileView has a new menu for mobile devices.

### CODE REVIEW

**Comment by ibotforwin** [comment]
Worked fine yesterday, when I try to run it today it shows:

Type 'boolean' is not assignable to type 'Element | ((element: Element) => Element) | null | undefined'.  TS2322

    71 |       }}
    72 |       keepMounted
  > 73 |       anchorEl={anchorEl}
       |       ^
    74 |       open={Boolean(anchorEl)}
    75 |       onClose={handleClose}
    76 |   >


Not familiar with TypeScript, so trying to debug the issue now.

**Comment by ibotforwin** [comment]
Changing UseState to:
`const [anchorEl, setAnchorE1]= useState<true|false>(false);`

Did not fix the issue.

**Comment by ibotforwin** [comment]
This last push includes initial mobile view. Got rid of anchorEl altogether, seems to be an ongoing issue with popovers in Material UI.

**Comment by hirokazutei** [comment]
Hello, thank you for the PR.
Would you be able to check out a new branch and create another PR?

**Pull request closed without merging**
